algoritmo "Função Se com Ou"
// Função :
// Autor :
// Seção de Declarações 
var

   cor : caracter

inicio

      Escreval ("Digite uma cor: ")
      leia (cor)
      
      Se ( cor = "Azul" ) ou ( cor = "Amarelo") Entao
      
           Escreval (" A cor digitada é Azul ou Amarelo")
      
      Senao
      
           Escreval (" Essa cor é Inválida ")
      
      FimSe

fimalgoritmo
