algoritmo "SE"
// Função :
// Autor :
// Seção de Declarações 
var


  numero : inteiro
   

inicio

       Escreval ("Digite um número: ")
       leia(numero)

      Se (numero > 10 ) Entao


           Escreval (numero, " é maior do que 10.")

  
      Senao
                    Escreval(numero, " é menor do que 10.")
                    
           FimSe

fimalgoritmo
